absolute_urls: false

home:
  alias: '/home'

pages:
  theme: night-rules
  process:
    markdown: true
    twig: false
  markdown:
    extra: true
    auto_line_breaks: true

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true

errors:
  display: 0
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true

languages:
  supported:
    - fr
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
